// <auto-generated />
using System;
using FastFoodOperator.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FastFoodOperator.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
<<<<<<<< HEAD:FastFoodOperator.Api/Data/Migrations/20250428170720_InitialCreate.Designer.cs
    [Migration("20250428170720_InitialCreate")]
    partial class InitialCreate
========
    [Migration("20250422152526_UpdateProductDeleteBehavior")]
    partial class UpdateProductDeleteBehavior
>>>>>>>> develop:FastFoodOperator.Api/Data/Migrations/20250422152526_UpdateProductDeleteBehavior.Designer.cs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FastFoodOperator.Api.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Burgers"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Drinks"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sides"
                        });
                });

            modelBuilder.Entity("FastFoodOperator.Api.Entities.Combo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Combos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 8.99m,
                            Name = "Cheeseburger Combo"
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 12.99m,
                            Name = "Cheeseburger Combo Deluxe"
                        });
                });

            modelBuilder.Entity("FastFoodOperator.Api.Entities.ComboProduct", b =>
                {
                    b.Property<int>("ComboId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductVariantId")
                        .HasColumnType("int");

                    b.HasKey("ComboId", "ProductId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("ComboProducts");

                    b.HasData(
                        new
                        {
                            ComboId = 1,
                            ProductId = 1
                        },
                        new
                        {
                            ComboId = 1,
                            ProductId = 2,
                            ProductVariantId = 1
                        },
                        new
                        {
                            ComboId = 1,
                            ProductId = 3,
                            ProductVariantId = 4
                        },
                        new
                        {
                            ComboId = 2,
                            ProductId = 1
                        },
                        new
                        {
                            ComboId = 2,
                            ProductId = 2,
                            ProductVariantId = 3
                        },
                        new
                        {
                            ComboId = 2,
                            ProductId = 3,
                            ProductVariantId = 6
                        });
                });

            modelBuilder.Entity("FastFoodOperator.Api.Entities.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PriceModifier")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Lettuce",
                            PriceModifier = 0.50m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tomato",
                            PriceModifier = 0.50m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Pickles",
                            PriceModifier = 0.25m
                        });
                });

            modelBuilder.Entity("FastFoodOperator.Api.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerNote")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            CustomerNote = "5kg extra onion",
                            OrderNumber = 1001,
                            OrderStatus = 2,
                            StartedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CompletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2024, 1, 2, 12, 0, 0, 0, DateTimeKind.Utc),
                            CustomerNote = "no peanuts",
                            OrderNumber = 1002,
                            OrderStatus = 0,
                            StartedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("FastFoodOperator.Api.Entities.OrderCombo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ComboName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderCombos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ComboName = "Bajs och kiss",
                            FinalPrice = 0m,
                            OrderId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 2,
                            ComboName = "Ägg och bacon",
                            FinalPrice = 0m,
                            OrderId = 2,
                            Quantity = 2
                        });
                });

            modelBuilder.Entity("FastFoodOperator.Api.Entities.OrderProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("ProductIngredients")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderProducts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FinalPrice = 0m,
                            OrderId = 1,
                            ProductIngredients = "[]",
                            ProductName = "Bajskorv",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 2,
                            FinalPrice = 0m,
                            OrderId = 1,
                            ProductIngredients = "[]",
                            ProductName = "Skurhinksmilkshake",
                            Quantity = 2
                        },
                        new
                        {
                            Id = 3,
                            FinalPrice = 0m,
                            OrderId = 2,
                            ProductIngredients = "[]",
                            ProductName = "Pannkakor",
                            Quantity = 3
                        });
                });

            modelBuilder.Entity("FastFoodOperator.Api.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PictureUrl")
                        .HasMaxLength(2048)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 5.99m,
                            CategoryId = 1,
                            Description = "A classic cheeseburger",
                            Name = "Cheeseburger",
<<<<<<<< HEAD:FastFoodOperator.Api/Data/Migrations/20250428170720_InitialCreate.Designer.cs
                            PictureUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRyp3wdwtBsAws86q4u0fyCPj12_SiSf9w6jQ&s"
========
                            PictureUrl = ""
>>>>>>>> develop:FastFoodOperator.Api/Data/Migrations/20250422152526_UpdateProductDeleteBehavior.Designer.cs
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 1.99m,
                            CategoryId = 2,
                            Description = "Refreshing soda",
                            Name = "Coke",
<<<<<<<< HEAD:FastFoodOperator.Api/Data/Migrations/20250428170720_InitialCreate.Designer.cs
                            PictureUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRyp3wdwtBsAws86q4u0fyCPj12_SiSf9w6jQ&s"
========
                            PictureUrl = ""
>>>>>>>> develop:FastFoodOperator.Api/Data/Migrations/20250422152526_UpdateProductDeleteBehavior.Designer.cs
                        },
                        new
                        {
                            Id = 3,
                            BasePrice = 2.99m,
                            CategoryId = 3,
                            Description = "Crispy golden fries",
                            Name = "French Fries",
<<<<<<<< HEAD:FastFoodOperator.Api/Data/Migrations/20250428170720_InitialCreate.Designer.cs
                            PictureUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRyp3wdwtBsAws86q4u0fyCPj12_SiSf9w6jQ&s"
                        },
                        new
                        {
                            Id = 4,
                            BasePrice = 5.99m,
                            CategoryId = 1,
                            Description = "Grilled beef patty with melted cheddar, lettuce, tomato & onion",
                            Name = "Classic Cheeseburger",
                            PictureUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRyp3wdwtBsAws86q4u0fyCPj12_SiSf9w6jQ&s"
                        },
                        new
                        {
                            Id = 5,
                            BasePrice = 7.49m,
                            CategoryId = 1,
                            Description = "Two beef patties, smoked bacon, American cheese, pickles & secret sauce",
                            Name = "Bacon Double Burger",
                            PictureUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRyp3wdwtBsAws86q4u0fyCPj12_SiSf9w6jQ&s"
                        },
                        new
                        {
                            Id = 6,
                            BasePrice = 6.99m,
                            CategoryId = 1,
                            Description = "Beef patty smothered in sautéed mushrooms and Swiss cheese",
                            Name = "Mushroom Swiss Burger",
                            PictureUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRyp3wdwtBsAws86q4u0fyCPj12_SiSf9w6jQ&s"
                        },
                        new
                        {
                            Id = 7,
                            BasePrice = 6.79m,
                            CategoryId = 1,
                            Description = "Peppered beef patty with pepper jack cheese, jalapeños & chipotle mayo",
                            Name = "Spicy Jalapeño Burger",
                            PictureUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRyp3wdwtBsAws86q4u0fyCPj12_SiSf9w6jQ&s"
                        },
                        new
                        {
                            Id = 8,
                            BasePrice = 7.19m,
                            CategoryId = 1,
                            Description = "Beef patty topped with crispy onion rings, cheddar & tangy BBQ sauce",
                            Name = "BBQ Onion Ring Burger",
                            PictureUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRyp3wdwtBsAws86q4u0fyCPj12_SiSf9w6jQ&s"
                        },
                        new
                        {
                            Id = 9,
                            BasePrice = 6.49m,
                            CategoryId = 1,
                            Description = "House-made black bean patty with avocado, lettuce & pico de gallo",
                            Name = "Black Bean Veggie Burger",
                            PictureUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRyp3wdwtBsAws86q4u0fyCPj12_SiSf9w6jQ&s"
========
                            PictureUrl = ""
>>>>>>>> develop:FastFoodOperator.Api/Data/Migrations/20250422152526_UpdateProductDeleteBehavior.Designer.cs
                        });
                });

            modelBuilder.Entity("FastFoodOperator.Api.Entities.ProductIngredient", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<bool>("Required")
                        .HasColumnType("bit");

                    b.HasKey("ProductId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("ProductIngredients");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            IngredientId = 1,
                            Required = true
                        },
                        new
                        {
                            ProductId = 1,
                            IngredientId = 2,
                            Required = true
                        },
                        new
                        {
                            ProductId = 3,
                            IngredientId = 3,
                            Required = false
                        });
                });

            modelBuilder.Entity("FastFoodOperator.Api.Entities.ProductVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PriceModifier")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductVariants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Small",
                            PriceModifier = 0m,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 2,
                            Name = "Medium",
                            PriceModifier = 1.49m,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Large",
                            PriceModifier = 2.49m,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "Small",
                            PriceModifier = 0m,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 5,
                            Name = "Medium",
                            PriceModifier = 1.49m,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 6,
                            Name = "Large",
                            PriceModifier = 2.49m,
                            ProductId = 3
                        });
                });

            modelBuilder.Entity("FastFoodOperator.Api.Entities.ComboProduct", b =>
                {
                    b.HasOne("FastFoodOperator.Api.Entities.Combo", "Combo")
                        .WithMany("ComboProducts")
                        .HasForeignKey("ComboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FastFoodOperator.Api.Entities.Product", "Product")
                        .WithMany("ComboProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FastFoodOperator.Api.Entities.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("ProductVariantId");

                    b.Navigation("Combo");

                    b.Navigation("Product");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("FastFoodOperator.Api.Entities.OrderCombo", b =>
                {
                    b.HasOne("FastFoodOperator.Api.Entities.Order", "Order")
                        .WithMany("OrderCombos")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("FastFoodOperator.Api.Entities.OrderProduct", b =>
                {
                    b.HasOne("FastFoodOperator.Api.Entities.Order", "Order")
                        .WithMany("OrderProducts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("FastFoodOperator.Api.Entities.Product", b =>
                {
                    b.HasOne("FastFoodOperator.Api.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FastFoodOperator.Api.Entities.ProductIngredient", b =>
                {
                    b.HasOne("FastFoodOperator.Api.Entities.Ingredient", "Ingredient")
                        .WithMany("ProductIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FastFoodOperator.Api.Entities.Product", "Product")
                        .WithMany("ProductIngredients")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FastFoodOperator.Api.Entities.ProductVariant", b =>
                {
                    b.HasOne("FastFoodOperator.Api.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FastFoodOperator.Api.Entities.Combo", b =>
                {
                    b.Navigation("ComboProducts");
                });

            modelBuilder.Entity("FastFoodOperator.Api.Entities.Ingredient", b =>
                {
                    b.Navigation("ProductIngredients");
                });

            modelBuilder.Entity("FastFoodOperator.Api.Entities.Order", b =>
                {
                    b.Navigation("OrderCombos");

                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("FastFoodOperator.Api.Entities.Product", b =>
                {
                    b.Navigation("ComboProducts");

                    b.Navigation("ProductIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
